name: Development CI

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      # client
      - name: Install client
        working-directory: client
        run: npm ci

      - name: Build client
        working-directory: client
        run: npm run build

      # server
      - name: Install server
        working-directory: server
        run: npm ci

      - name: Prisma generate
        working-directory: server
        run: npx prisma generate

      - name: Build server
        working-directory: server
        run: npm run build || echo "no build"